### ISSUE TITLE
import Lattce2 doesn't work in Gui-less FreeCAD

### ISSUE THREAD

**Issue by DeepSOIC** [DeepSOIC/Lattice2#12]

**Comment by DeepSOIC** [comment]
Hi, thanks for posting. I feel there is demand for gui-less Lattice, hopefully I find time to do it in near future.

**Comment by susnicek** [comment]
Yes indeed, for example for me it is important for geometry optimization along with FEM module. The optimization loop runs in gui-less mode...
Thanks in advance for your effort!

**Comment by DeepSOIC** [comment]
I did something. It may be working now. Apologies in advance, I did very little testing.

**Comment by DeepSOIC** [comment]
No feedback for a while... I assume it fixed. Reopen if necessary.
