### ISSUE TITLE
Macro not recorded for Explode Compound

### ISSUE THREAD

**Issue by PatONeil** [DeepSOIC/Lattice2#2]
When recording a macro and using Lattice2 Explode Compound, the operation is not recorded.   Is there any manual way to add this code to a macro?  If so please send to me at oneilpatr at gmail dot com

Thanks

**Comment by DeepSOIC** [comment]
Hi!

There was some problem with coding it... I'll take another look.

A quick way to include that into a macro is

    Gui.Selection.clearSelection()
    Gui.Selection.addSelection(App.ActiveDocument.ActiveObject)
    Gui.runCommand("Lattice2_Explode")

**Comment by PatONeil** [comment]
Thanks for the quick response.   I needed to modify the selection statement
but other than that, it works great.

 

Pat

PS:  This is a great plug-in.  I don't know how I would have created my part
without it.

 

  _____
