### ISSUE TITLE
Lattice2 does not work in FreeCAD 0.18.1

### ISSUE THREAD

**Issue by burbilog** [DeepSOIC/Lattice2#29]
FreeCAD 0.18.1 complains when I try to use Lattice2: 

    invalid literal for int() with base 10: '18.1'

It seems that lattice2's version check does not understand x.x.x format.

**Comment by DeepSOIC** [comment]
Thanks for reporting, will fix.

In the meantime, you can use Lattice2 with FC 0.19dev

**Comment by DeepSOIC** [comment]
Should be fixed, please test.

**Comment by burbilog** [comment]
Yep, thanks. It works now.
