### ISSUE TITLE
Update to new FreeCAD AddonManager metadata schema

### ISSUE THREAD

**Issue by luzpaz** [DeepSOIC/Lattice2#54]
Please see https://github.com/FreeCAD/FreeCAD-addons/issues/200

BTW, @DeepSOIC can you also do the same fo PartoMagic WB? :stuck_out_tongue_winking_eye:

**Comment by luzpaz** [comment]
@DeepSOIC ping

**Comment by luzpaz** [comment]
:disappointed:

**Comment by DeepSOIC** [comment]
i'm sorry, i'm too lazy
