### ISSUE TITLE
Lattice Icons have weird location in Linkstage.

### ISSUE THREAD

**Issue by HaasNL2** [DeepSOIC/Lattice2#65]
I am working on an icon theme for Linkstage.
And it goes pretty good, but now there is a pattern Icon from Lattice2 on the part workbench. And since I like to have it complete I wanted to mod that one. But I couldn't.
It has a weird location link. I have no idea if it is an error in Linkstage or that it is the workbench. But maybe it rings you some bells if you see it. Normal icons don't have the :/icons/ in front of the location. And I guess the : breaks the iconset config file. I checked some other Workbenches like surface and path they all have normal resource paths.

![afbeelding](https://user-images.githubusercontent.com/29804962/167204120-1ef509a4-123d-4e12-85fb-36fda2253bec.png)

If you have Linkstage installed and want to see it yourself you can do as followed:
![afbeelding](https://user-images.githubusercontent.com/29804962/167204913-33f380ba-7f1e-4e2e-bdff-ab9fa743ec97.png)

new icon:
![PartDesign_Lattice2_PDPattern](https://user-images.githubusercontent.com/29804962/167204644-b19fe5b0-5da8-49ae-8df3-afab309f495e.png)

**Comment by DeepSOIC** [comment]
i don't understand icon locations, unfortunately. Here's an issue/PR on Part-o-magic: https://github.com/DeepSOIC/Part-o-magic/pull/54
Any help in sorting out this mess is appreciated.

**Comment by DeepSOIC** [comment]
also, i think your new icon is conceptually incorrect (suggests that Lattice Pattern copies bodies, while it actually copies features).

**Comment by HaasNL2** [comment]
> also, i think your new icon is conceptually incorrect (suggests that Lattice Pattern copies bodies, while it actually copies features).

I will add some changes, I tried the function first before making the icon but but you re right that it uses function, although it is hard to make it visible is such a small picture. I'll poke around for the icons, not a python programmer. But I compared path workbench and yours to see any difference but didn't.

**Comment by HaasNL2** [comment]
Ok I made a mistake there was a typo it does work.
